all:
	$(MAKE) -f Makefile.1xx install
	$(MAKE) -f Makefile.hge install
	$(MAKE) -f Makefile.input install

1xx:
	$(MAKE) -f Makefile.1xx install
	$(MAKE) -f Makefile.hge install
	$(MAKE) -f Makefile.input install

3xx:
	$(MAKE) -f Makefile.3xx install
	$(MAKE) -f Makefile.hge install
	$(MAKE) -f Makefile.input install

clean:
	$(MAKE) -f Makefile.1xx clean
	$(MAKE) -f Makefile.3xx clean
	$(MAKE) -f Makefile.hge clean
	$(MAKE) -f Makefile.input clean
